# PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simon-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simon-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simon-guestbook
      component: postgres
  template:
    metadata:
      labels:
        app: simon-guestbook
        component: postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/fedora/postgresql-16:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 512Mi
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: simon-db-password
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: simon-db-password
                  key: password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: simon-db-config
                  key: db-name
          volumeMounts:
            - name: simon-postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: simon-postgres-data
          persistentVolumeClaim:
            claimName: simon-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: simon-postgres
spec:
  type: ClusterIP
  selector:
    app: simon-guestbook
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simon-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: lvms-vg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simon-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simon-guestbook
      component: redis
  template:
    metadata:
      labels:
        app: simon-guestbook
        component: redis
    spec:
      containers:
        - name: redis
          image: quay.io/kurs/redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 512Mi
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: simon-redis-password
                  key: password
          volumeMounts:
            - name: simon-redis-data
              mountPath: /var/lib/redis/data
      volumes:
        - name: simon-redis-data
          persistentVolumeClaim:
            claimName: simon-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: simon-redis
spec:
  type: ClusterIP
  selector:
    app: simon-guestbook
    component: redis
  ports:
    - port: 6379
      targetPort: 6379

# Golang Backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simon-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simon-guestbook
      component: backend
  template:
    metadata:
      labels:
        app: simon-guestbook
        component: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/rafaelnacho1/guestbook:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 512Mi
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: simon-db-config
                  key: db-host
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: simon-db-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: simon-db-config
                  key: redis-port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: simon-redis-password
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: simon-backend
spec:
  type: ClusterIP
  selector:
    app: simon-guestbook
    component: backend
  ports:
    - port: 8080
      targetPort: 8080
